const dishes = [
  {
    name: "French Special Pasta",
    price: 13.0,
    rating: 5,
    reviews: 120,
    desc: "Enjoy rich, creamy, authentic French flavors seasoned to your plate.",
    img: "pasta.png",
    category: "pasta",
  },
  {
    name: "French Special Burger",
    price: 13.0,
    rating: 5,
    reviews: 150,
    desc: "Bite into a juicy, flavorful burger with French twist, loaded with fresh ingredients and secret sauces.",
    img: "burger.png",
    category: "burger",
  },
  {
    name: "Italian Breakfast",
    price: 13.0,
    rating: 5,
    reviews: 100,
    desc: "Start your day with a delicious Italian breakfast, featuring classic flavors and wholesome ingredients.",
    img: "fast-food.png",
    category: "fast-foods",
  },
  {
    name: "American Burger",
    price: 13.0,
    rating: 5,
    reviews: 140,
    desc: "Enjoy a juicy, flavorful American burger packed with fresh ingredients and served to perfection.",
    img: "burger.png",
    category: "burger",
  },
  {
    name: "Indian Sandwich",
    price: 13.0,
    rating: 5,
    reviews: 110,
    desc: "Taste the vibrant spices and hearty flavors of a traditional Indian sandwich, made to satisfy every craving.",
    img: "sandwich.png",
    category: "sandwich",
  },
  {
    name: "French Special Pasta",
    price: 13.0,
    rating: 5,
    reviews: 130,
    desc: "Delight in the creamy, rich features of our French special pasta, crafted with authentic ingredients and flavors.",
    img: "pasta.png",
    category: "pasta",
  },
  {
    name: "Thali Special",
    price: 15.0,
    rating: 4.8,
    reviews: 90,
    desc: "A complete Indian meal with a variety of dishes, rice, and breads.",
    img: "thali.png",
    category: "thali",
  },
  {
    name: "Fast Food Combo",
    price: 10.0,
    rating: 4.5,
    reviews: 200,
    desc: "Quick and tasty fast food options including fries and a drink.",
    img: "fast-food.png",
    category: "fast-foods",
  },
  {
    name: "Veggie Sandwich",
    price: 12.0,
    rating: 4.7,
    reviews: 85,
    desc: "Fresh veggies and herbs in a toasted sandwich.",
    img: "sandwich.png",
    category: "sandwich",
  },
  {
    name: "Spicy Thali",
    price: 16.0,
    rating: 4.9,
    reviews: 105,
    desc: "Spicy Indian thali with curries and sides.",
    img: "thali.png",
    category: "thali",
  },
  {
    name: "Cheese Pasta",
    price: 14.0,
    rating: 4.6,
    reviews: 95,
    desc: "Creamy cheese pasta with herbs.",
    img: "pasta.png",
    category: "pasta",
  },
  {
    name: "Double Burger",
    price: 15.0,
    rating: 4.8,
    reviews: 160,
    desc: "Double patty burger with extra cheese.",
    img: "burger.png",
    category: "burger",
  },
];
// Global cart state
let cart = [];
let currentCategory = "all";
let visibleCount = 6;
